<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>Resolvai.Api</RootNamespace>
    <UserSecretsId>resolvai-api</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Resolvai.Application\Resolvai.Application.csproj" />
    <ProjectReference Include="..\Resolvai.Infrastructure\Resolvai.Infrastructure.csproj" />
  </ItemGroup>

</Project>
